### ISSUE TITLE
Why gatsby over metalsmith for the blog?

### ISSUE THREAD

**Issue by bananatranada** [segmentio/metalsmith#288] opened 2017-07-17 12:40 UTC
Could you guys go in depth about the choice of moving the blog over to gatsby?

What would you recommend and for what purposes?

**Comment by Ajedi32** [comment] 2017-07-17 16:14
Could you clarify what site you're referring to? Pretty sure the regular metalsmith.io site is built with Metalsmith.

**Comment by bryankang** [comment] 2017-07-17 18:25
@Ajedi32 Here's the [link](https://www.gatsbyjs.org/blog/gatsby-v1/) that says the segment blog was built with gatsby. Metalsmith being perfectly suited for a blog and open sourced by segment, I was wondering why they went with gatsby.

**Comment by Ajedi32** [comment] 2017-07-17 19:14
I'm not affiliated with Segment so I can't really comment on why they went with Gatsby. At first glance though it looks to me like Gatsby is far more opinionated than Metalsmith is. Metalsmith's core is tiny and relies almost entirely on plugins for its functionality, whereas Gatsby seems to try to include a lot more functionality out of the box, so maybe that has something to do with it.

**Comment by kylenstone** [comment] 2017-09-02 23:07
Motion to close this issue...

**Comment by up0** [comment] 2017-09-06 21:35
Since Segment has chosen Gatsby over its own Metalsmith, there is a concern for longevity of this project, and what the future could hold.   As a new user, I wouldn't choose Metalsmith if Segment wasn't dogfooding, i.e. using its own project, because there's a huge risk that this project can be shuttered, leaving many Metalsmith users out in the cold.

**Comment by Ajedi32** [comment] 2017-09-08 03:56
@up0 Segment isn't the sole maintainer of Metalsmith. There are several maintainers such as myself who don't work for Segment.

Not to mention the Metalsmith core is pretty minimal. I'm certain that anyone with a solid grasp of Node and a little free time on their hands would have no trouble keeping Metalsmith afloat all on their own; for these reasons the longevity of the project isn't really much of a concern.

**Comment by leviwheatcroft** [comment] 2017-09-11 06:23
Lets not read too much into it.. whoever was tasked with building the blog had a preference for Gatsby, no big deal.

**Comment by otterpro** [comment] 2017-09-12 14:20
Awesome. Glad to hear from the supporters.  Definitely moving forward with Metalsmith-based projects.

**Comment by kosirm** [comment] 2017-12-25 23:56
I really like metalsmith for it's simplicity, but adding it all together: no new version since last year + segment blog built on gatsby + metalsmith.io down because they "forgot" to update heroku account... It all looks like there is no real interest in segment to lead this project further. Pretty sad conclusion for me as user. Hopefully other maintainers could move project forward, because it is so valuable project!

**Comment by Zearin** [comment] 2018-05-28 16:16
@kosirm I don’t want to see this project die, either.  That was part of my motivation for opening #303 .

@Ajedi32 and other maintainers must review my work first, but I’m hoping it will become the basis for Metalsmith 3.  If that happens, my hope is that the community will notice and interest will be revived.  

With enough interest and contributions, hopefully we can bring most or all of the Metalsmith ecosystem into modern JavaScript. 

(And—hopefully—drop support for ancient versions of Node, too!  Every time I run `npm audit` I smile a little.  Just one small-but-fantastic part of the many leaps and bounds that Node.js and NPM have  made since Metalsmith came onto the scene. ☻)

**Comment by Zearin** [comment] 2018-05-28 16:18
_(**Also:** “Metalsmith” is just so much better of a name than “Gatsby”. 👅 )_

**Comment by itsMeBender** [comment] 2018-06-01 08:56
Hmm, after reading this. And the project problems I have, with my first Metalsmith try-out. I'm not sure to continue. I'm very fond of NodeJS based solutions, but if it doesn't work...

**Comment by Zearin** [comment] 2018-06-01 14:28
@itsMeBender What problems are you having?  I’d like to help!

**Comment by itsMeBender** [comment] 2018-06-04 09:43
@Zearin , Thank you!
I am trying to build a Metalsmith static site from the ground up (no experience at all). Looking for information on the web, I found this site: [How to Create a Static Site with Metalsmith](https://www.sitepoint.com/create-static-site-metalsmith/). But following these steps, my project didn't work. 
But his project can be downloaded here [Metalsmith demo](https://github.com/craigbuckler/metalsmith-demo). This demo of Metalsmith works! But relies on old Metalsmith node modules. As declared in packages.js.

When I copy those, old node modules, into my own project. My project works! So my project setup, etc. is good enough, to build a Metalsmith static site. Based on old module versions.

When I upgrade my project to the latest versions of the metalsmith modules. It fails again!

I got these error messages: 
Error: no files to process. See https://www.npmjs.com/package/metalsmith-in-place#no-files-to-process
or
Error: no files to process. See https://www.npmjs.com/package/metalsmith-layouts#no-files-to-process

Solving this problem, with information from GitHub readme's does not help. Only, copying back the old modules, download by the demo. Solves the problem.

Working packages;
    "handlebars": "^4.0.5",
    "metalsmith": "^2.1.0",
    "metalsmith-assets": "^0.1.0",
    "metalsmith-browser-sync": "^1.1.0",
    "metalsmith-collections": "^0.7.0",
    "metalsmith-feed": "^0.2.0",
    "metalsmith-html-minifier": "^2.0.0",
    "metalsmith-in-place": "^1.4.3",
    "metalsmith-layouts": "^1.6.4",
    "metalsmith-mapsite": "^1.0.4",
    "metalsmith-markdown": "^0.2.1",
    "metalsmith-permalinks": "^0.5.0",
    "metalsmith-publish": "^0.1.3",
    "metalsmith-word-count": "0.0.4"

current metalsmith-in-place "^4.1.1"
current metalsmith-layouts "^2.1.0"

So what is changed in those major releases; API?, Configuration? ...

**Comment by Zearin** [comment] 2018-06-04 15:11
Tell me if any of my statements are incorrect.  

Here is what I understand so far…

# Current Situation

Okay, so you say that the outdated—but working—demo, uses:

* `metalsmith-in-place ^1.4.3`
* `metalsmith-layouts ^1.6.4`

But things break when you update to:

* `metalsmith-in-place ^1.4.3`
* `metalsmith-layouts ^2.1.0`

# Tracking Down the Problem

The first thing I did was go to [metalsmith-in-place’s `CHANGELOG.md`](https://github.com/ismay/metalsmith-in-place/blob/master/CHANGELOG.md).

In that changelog, under [`v2.0.0-beta.1`](https://github.com/ismay/metalsmith-in-place/blob/master/CHANGELOG.md#200-beta1---september-11-2016), it says:

> * switch to jstransformers for rendering (breaking change)

That sounded familiar to me, so I checked the [link you provided](https://www.npmjs.com/package/metalsmith-in-place#no-files-to-process).  That page says the errors are always caused by one of the following:

> * Your pattern does not match any files
> * None of your files pass validation, validation fails for files that:
>     - Have no extension
>     - Are not utf-8
>     - Need a jstransformer that hasn't been installed

Aha!  So it looks like the error is JSTransformer related.


# Possible Solution

In order for `metalsmith-in-place` to work, you need to install the appropriate JSTransformers.  [This section of the `metalsmith-in-place` README.md](https://github.com/ismay/metalsmith-in-place#2-install-appropriate-jstransformers) explains how it works.

I think you will need to _at least_ do the following:

```
npm rm --save handlebars
npm install --save jstransformer-handlebars
```

You _might_ need to do something similar for markdown as well, but it’s hard for me to say without access to your project.

**Comment by itsMeBender** [comment] 2018-06-05 07:21
Hi, thank you for your support.
I already had the the same line of thoughts. I also red the documentation about the jstransformer modules and tried it also. But no luck here.

my test setup:
`
  "devDependencies": {
    "jstransformer-handlebars": "^1.1.0",
    "jstransformer-html": "^0.1.0",
    "jstransformer-markdown-it": "^2.1.0",
    "metalsmith": "^2.3.0",
    "metalsmith-autotoc": "^0.1.5",
    "metalsmith-in-place": "^4.1.1",
    "metalsmith-layouts": "^2.1.0",
    "metalsmith-markdown": "^0.2.2"
  }
`
Same error "Error: no files to process. See https://www.npmjs.com/package/metalsmith-in-place#no-files-to-process"

The documentation mentioned a JSON config file. But I'm using a build script. May be it's then the configuration;
`
var
	consoleLog = true, // set true for metalsmith file and meta content logging
	// modules
	debug		= require('./lib/metalsmith-debug'),
	inplace		= require('metalsmith-in-place'),
	layouts		= require('metalsmith-layouts'),
	markdown	= require('metalsmith-markdown'),
	metalsmith	= require('metalsmith');

var
	templateConfig = {
		engine: 'handlebars',
		default: 'layout.html',
		directory: './src/layout/',
		engineOptions: {
			"cache": false
		},
		partials: './src/partials/',
		pattern: '**/*'
	}

metalsmith(__dirname)
	.clean(true)
	.source('./src/html/')
	.destination('./build/')
	.use(markdown())
	.use(inplace(templateConfig))
	.use(layouts(templateConfig))
	.build(function(err) {
	if (err) throw err;
		console.log('Build finished!');
	});
`

**Comment by Zearin** [comment] 2018-06-05 15:22
Can you put the project somewhere I can get a copy of it?  I’ll see if I can figure out what’s going on here.

**Comment by itsMeBender** [comment] 2018-06-06 09:41
@Zearin - https://github.com/itsMeBender/pr-metalsmith

**Comment by itsMeBender** [comment] 2018-06-07 10:14
Thank you @Zearin, with your __step through__ problem solving approach. I finally solved my problems. 
In your description above, you're forgot to mention the installation of  `jstransformer-handlebars`  

> npm i --save jstransformer-handlebars

I copied your approach of problem solving into my project as WIKI. See [GitHub](https://github.com/itsMeBender/pr-metalsmith/wiki). It will be useful for other people, I think.

**Comment by borisovg** [comment] 2019-03-31 17:44
If anyone is interested, I made this blog site example: https://github.com/borisovg/metalsmith-blog-example, which is a simplified version of what I use for building my own site.

Demo: https://borisovg.github.io/metalsmith-blog-example-demo/

**Comment by woodyrew** [comment] 2019-04-11 08:52
I'm unsure why Segment decided to use Gatsby for their blog. As most of the maintainers are not employee's or no longer employees of Segment it is hard to know the answer.

As Ajedi32 said (https://github.com/segmentio/metalsmith/issues/288#issuecomment-315853246) Gatsby and Metalsmith have very different approaches with different pros and cons. As Segment haven't answered the question thus-far I suspect they're not likely to so I'll close this issue.

**Closed** 2019-04-11 08:52 UTC
Labels: question

**Comment by erichonkanen** [comment] 2019-05-14 20:50
@itsMeBender @Zearin just landed here and ran into same `no file to process` error, which was finally resolved after finding this thread and adding `npm i --save jstransformer-handlebars`. Perhaps it would be useful to add that to the main metalsmith doc site for other people new to the project and using handlebars?
