### ISSUE TITLE
Reading front matter with duplicate properties fails silently

### ISSUE THREAD

**Issue by M5150** [segmentio/metalsmith#279] opened 2017-02-09 18:04 UTC
If duplicate front matter properties are specified within a source file no properties are assigned on the resource and no error (AFAIK) is thrown. I found a related issue in the grey-matter repo with a potential fix. [https://github.com/jonschlinkert/gray-matter/issues/28](url)

**Comment by Ajedi32** [comment] 2017-02-09 18:47
Duplicate of #226

**Closed by Ajedi32** 2017-02-09 18:47 UTC
