### ISSUE TITLE
Plugin version rot

### ISSUE THREAD

**Issue by pikeas** [segmentio/metalsmith#123] opened 2015-02-25 02:06 UTC
I'm new to the Metalsmith ecosystem, so I've been combing through the various plugins to find the ones I need. I'm primarily interested in pre- and post-processing transformations on my styles and scripts. This means that Metalsmith plugins are an intermediate dependency wrapping the real depepency on, e.g, `autoprefixer` or `coffee-script`.

Unfortunately, many of the inner dependencies are months out-of-date. This is a big issue, given the rapidly developing front-end ecosystem. `peerDependencies` in a future version of Node will help with this, but that's at worst a hypothetical solution and at best a long way off.

Many of these plugins are just 20-100 LOC, which is tempting me to just copy them into my own plugins directory. However, summed over a dozen plugins, this becomes a maintenance nightmare.

I don't have a proposal for a great solution, but I wanted to voice the problem. One option is to bring the most popular plugins under direct management by SegmentIO/Metalsmith. This is, of course, more work, but Metalsmith has also quickly become one of the most used static site generators (by GH stars).

Another option is to extend the Metalsmith core. Many of these plugins basically take a subset of files, output a transform, and usually drop the originals. This might sound like I'm suggesting Metalsmith become more like Gulp, which I suppose I am. But consider this excerpt from an excellent SO answer:

> It's true that Gulp has certain advantages over Metalsmith. Ease of writing plugins, sadly, is not one of them. Creating new files from a Gulp plugin is harder than it should be, as is correct error handling. There's also a strong impedance mismatch between the streaming approach, and the nature of static sites to need cross-file operations.

> [...]For these kind of tasks, the Metalsmith plugin API is unequivocally superior to Gulp's. [...]Basically, Metalsmith is really the Gulp of static site generators, while Gulp is the Gulp of streaming build systems. And you can combine the strengths of both, using Gulpsmith."

> (http://stackoverflow.com/questions/23227248/is-there-some-gulp-plugin-that-lets-it-perform-the-function-of-a-static-site-gen/23858857#23858857)

So perhaps there's a cleaner way to take advantage of gulp's stronger, more active plugin ecosystem? And if not, how about an improved plugin infrastructure that abstracts out a lot of the plugin boilerplate? What if we could do..

    Metalsmith(__dirname).
        .process({files: ['styles/screen.styl'], processors: [stylus(), autoprefixer(), csso()]})
        .process({files: ['scripts/app.coffee'], processors: [coffee(), coffeelint(), uglify()]})
        .build()
    )

I'm extremely new to Metalsmith, so I hope none of the above is totally off-base!

**Comment by unstoppablecarl** [comment] 2015-02-25 14:44
I have not used this but it seems to be similar to what you describe https://github.com/pjeby/gulpsmith

**Comment by ianstormtaylor** [comment] 2015-02-26 08:08
What kinds of things are you seeing rotting? My guess it was around the `1.0` release which had some backwards incompatibility? I don't really foresee any further backwards incompatibility though so it seems like fixing them would be a single-time thing, at least for the foreseeable future. What do you think?

**Comment by pikeas** [comment] 2015-03-12 00:36
@ianstormtaylor It's not that the plugins are incompatible with Metalsmith. It's that the plugins are sporadically maintained, resulting in really stale versions for the underlying tools.

Example #1: metalsmith-jade uses Jade version 1.8.2. This was released in December. There have been three releases since then, the current version is 1.9.2.
Example #2: metalsmith-stylus uses Stylus version 0.47.1. This was released in July, *eight* months ago. This is nine releases behind the current version, 0.50.0.

This makes the plugin system as currently implemented a bit broken. Either "core" plugins need to be actively maintained, or the use of plugins which heavily depend on external libs should be heavily discouraged.

**Comment by ianstormtaylor** [comment] 2015-03-12 01:20
Ahhh gotcha. I think those plugins should be updated to not list `jade` or `stylus` directly in their `package.json`, so that it takes whatever the user has pegged as their version instead from the top-level dependencies. That's what used to happen with other Jade plugins we used to use for `component` at least and it seemed to work well.

**Comment by ianstormtaylor** [comment] 2015-03-28 01:22
Closing with that fix ^

**Closed by ianstormtaylor** 2015-03-28 01:22 UTC

**Comment by pikeas** [comment] 2015-03-28 01:56
@ianstormtaylor That's not a fix until those packages actually change. Feels a bit like punting on the issue. As the parent project, Metalsmith should take responsibility for, and monitor progress on, a change expected to occur at the plugin level.

**Comment by ianstormtaylor** [comment] 2015-03-28 18:18
@pikeas Actually, the whole point of the Metalsmith's core being so simple (`~250` lines) is because plugins aren't its responsibility—by design. When opinionated plugins become the responsibility of a core library, the core library slowly becomes more opinionated and more complex over time.

Those packages are maintained by people (some may even be maintained by me) who are capable of merging any pull request you make, or writing the fixes themselves, assuming they agree. If you want to point them this closed issue to help explain the logic for unpegging the versions, that sounds good to me!
