### ISSUE TITLE
Rebuild problems

### ISSUE THREAD

**Issue by gpedro** [segmentio/metalsmith#134] opened 2015-04-22 06:04 UTC
I'm trying to put another watcher and is going a very strange error. When trying to rebuild, it is loading content as name .html file.

My code: https://github.com/gpedro/conf-boilerplate/tree/fix/metalsmith-watch

to build on startup it works perfectly, but to change any file and trying rebuild, it happens this:
![](http://i.imgur.com/qnyC7yf.png)

**Comment by MoOx** [comment] 2015-05-05 10:25
@ianstormtaylor this commit https://github.com/segmentio/metalsmith/commit/19af5486a66a6f4c9d8f8c3cec5d0301b035f02d has introduced a breaking change to the public api https://github.com/segmentio/metalsmith#runfiles-fn which doesn't respect semver.
I am not familiar yet with generators, and since you use unyield, I am not sure if we can adjust the api depending on the presence of `plugins` parameter when `#run()` is called.

@gpedro fyw, I am working on [metalsmith-watch v1.0.0](https://github.com/FWeinb/metalsmith-watch/pull/19) which will solves a lot of problem for partials rebuild.

**Comment by MoOx** [comment] 2015-05-08 04:18
@ianstormtaylor I am not sure you did actually broke somethings. But I am definitly having differences with run() method that seems to not work as expected (it's like a done() callback is never executed when `yield run()` is called in `prototype.run()`. I added some stupid console.log() after this method and it's never outputed. cpu isn't high so not sure what is wrong. Maybe a recent changes to a dep of a dep...
I am very new to generators so if you have any idea for this regression, your are welcome :)
I will continue my investigation.

**Comment by MoOx** [comment] 2015-05-08 04:42
I hate when you resolve an issue by doing `rm -rf node_modules && npm i`... Sorry for the noize.

**Comment by ianstormtaylor** [comment] 2015-05-08 14:33
Haha no worries man, I know that feeling. Sorry for the headache regardless.

**Comment by gpedro** [comment] 2015-05-18 00:11
@MoOx the problems persist with metalsmith-watch v1.0.1

![gif](http://i.imgur.com/0xRTx1c.gif)

**Comment by MoOx** [comment] 2015-05-18 03:46
From what I see, you did not upgrade the configuration of metalsmith-watch https://github.com/FWeinb/metalsmith-watch#paths-default-source-true

**Comment by gpedro** [comment] 2015-05-18 05:20
@MoOx 
> I hate when you resolve an issue by doing rm -rf node_modules && npm i... Sorry for the noize.

https://github.com/gpedro/conf-boilerplate/commit/9e540ded7b73b3fb12124ef4dccadecef5f8ae69
now it does not show the error, but not updated.

![gif](http://i.imgur.com/PM6CxV3.gif)

**Comment by MoOx** [comment] 2015-05-18 05:23
Maybe using this might help... https://github.com/FWeinb/metalsmith-watch#livereload-default-false

**Comment by gpedro** [comment] 2015-05-18 05:29
@MoOx 
https://github.com/gpedro/conf-boilerplate/commit/862a0766af0d8fb71b4fc866043d89be6ec46031

![gif](http://i.imgur.com/KtAxMMT.gif)

**Comment by MoOx** [comment] 2015-05-18 05:32
Please read the fucking documentation https://github.com/FWeinb/metalsmith-watch#paths-default-source-true
Issues are not a hotline
You just don't use the module as the doc explains.

**Comment by gpedro** [comment] 2015-05-18 05:41
@MoOx holy crap. sorry for that.
https://github.com/gpedro/conf-boilerplate/commit/ebd09c78093a4e8765f34bc7c8fe7c36fddcecdf

![gif](http://i.imgur.com/iydcFtM.gif)

**Comment by MoOx** [comment] 2015-05-18 05:43
You don't read correctly again....

**Comment by gpedro** [comment] 2015-05-18 05:50
@MoOx lol

he are watching `src/**/*`  and rebuilding `**/*` when changed. But the problems is: he are using content instead filename.

```
[metalsmith-watch] ✔︎ src/layouts/default.html changed
[metalsmith-watch] - Updating 17 files...
[metalsmith-watch] ✗ Error: ENOENT, open '/Users/gpedro/bp-fix/src/layouts/{{#if forkButton}}
  <a href="{{ forkButton.repository }}" class="github-link">
    <img src="https:/s3.amazonaws.com/github/ribbons/forkme_right_white_ffffff.png" alt="Fork me on GitHub">
  </a>
{{/if}}

<!-- HEADER -->
<header class="header">
  <div class="wrapper">
    <h1 class="logo-name">
      <a class="logo-link" href="#" title="{{ conf.name }}" itemprop="name">{{ conf.name }}</a>
    </h1>
    <h2 class="tagline">{{ conf.date }}, {{ conf.venue }}, {{ conf.city }}</h2>

    <div class="call-action-area">
      {{#if conf.price }}
        <span class="price">Only {{ conf.price }}</span>
      {{/if}}

      {{#if callToAction }}
        <a href="{{ callToAction.link }}" class="call-action-link" title="{{ callToAction.text }}">{{ callToAction.text }}</a>
      {{/if}}
    </div>
  </div>
</header>
<!--  / HEADER -->

<hr>
.html'
```

**Comment by MoOx** [comment] 2015-05-18 05:57
You are completly wrong about how to use metalsmith. Your templates have nothing to do as source files. Please just take 5min to read the entire readme of metalsmith-watch and pay attention to the `paths` option and the example that involve the template directory.
Tempaltes & partials should not be read as metalsmith sources. So whether you use metalsmith.source("src/documents), whether you move your layouts of the src folder and you read again https://github.com/FWeinb/metalsmith-watch#paths-default-source-true

@ianstormtaylor I think you should close this issue, the current problem is clearly pebkac :)

**Closed** 2015-07-11 20:39 UTC
